import { BoxIcon, ImageIcon, VideoIcon } from "lucide-react";
import {
  BsFiletypeExe,
  BsFiletypePdf,
  BsFiletypeDoc,
  BsFiletypeDocx,
  BsFiletypeXls,
  BsFiletypeXlsx,
  BsFiletypePpt,
  BsFiletypePptx,
  BsFiletypeCsv,
  BsFiletypeTxt,
  BsFiletypeJson,
  BsFiletypeXml,
  BsFiletypeHtml,
  BsFiletypeCss,
  BsFiletypeJs,
  BsFiletypePy,
  BsFiletypeJava,
  BsFiletypePhp,
  BsFiletypeSh,
  BsFiletypeMp3,
  BsFiletypeMp4,
  BsFiletypePng,
  BsFiletypeJpg,
  BsFiletypeGif,
  BsFiletypeSvg,
  BsFiletypeMd,
  BsFiletypeTsx,
  BsFileZip,
} from "react-icons/bs";

const extensionIconMap: Record<string, JSX.Element> = {
  jpg: <BsFiletypeJpg className="w-4 h-4" />,
  jpeg: <BsFiletypeJpg className="w-4 h-4" />,
  png: <BsFiletypePng className="w-4 h-4" />,
  gif: <BsFiletypeGif className="w-4 h-4" />,
  bmp: <ImageIcon className="w-4 h-4" />,
  svg: <BsFiletypeSvg className="w-4 h-4" />,
  webp: <ImageIcon className="w-4 h-4" />,
  mp4: <BsFiletypeMp4 className="w-4 h-4" />,
  mov: <VideoIcon className="w-4 h-4" />,
  avi: <VideoIcon className="w-4 h-4" />,
  mkv: <VideoIcon className="w-4 h-4" />,
  webm: <VideoIcon className="w-4 h-4" />,
  mp3: <BsFiletypeMp3 className="w-4 h-4" />,
  wav: <BsFiletypeMp3 className="w-4 h-4" />,
  flac: <BsFiletypeMp3 className="w-4 h-4" />,
  ogg: <BsFiletypeMp3 className="w-4 h-4" />,
  aac: <BsFiletypeMp3 className="w-4 h-4" />,
  m4a: <BsFiletypeMp3 className="w-4 h-4" />,
  pdf: <BsFiletypePdf className="w-4 h-4" />,
  doc: <BsFiletypeDoc className="w-4 h-4" />,
  docx: <BsFiletypeDocx className="w-4 h-4" />,
  xls: <BsFiletypeXls className="w-4 h-4" />,
  xlsx: <BsFiletypeXlsx className="w-4 h-4" />,
  ppt: <BsFiletypePpt className="w-4 h-4" />,
  pptx: <BsFiletypePptx className="w-4 h-4" />,
  csv: <BsFiletypeCsv className="w-4 h-4" />,
  txt: <BsFiletypeTxt className="w-4 h-4" />,
  md: <BsFiletypeMd className="w-4 h-4" />,
  json: <BsFiletypeJson className="w-4 h-4" />,
  xml: <BsFiletypeXml className="w-4 h-4" />,
  html: <BsFiletypeHtml className="w-4 h-4" />,
  css: <BsFiletypeCss className="w-4 h-4" />,
  js: <BsFiletypeJs className="w-4 h-4" />,
  tsx: <BsFiletypeTsx className="w-4 h-4" />,
  py: <BsFiletypePy className="w-4 h-4" />,
  java: <BsFiletypeJava className="w-4 h-4" />,
  php: <BsFiletypePhp className="w-4 h-4" />,
  rb: <BsFiletypePhp className="w-4 h-4" />,
  go: <BsFiletypePhp className="w-4 h-4" />,
  sh: <BsFiletypeSh className="w-4 h-4" />,
  bat: <BsFiletypeSh className="w-4 h-4" />,
  zip: <BsFileZip className="w-4 h-4" />,
  rar: <BsFileZip className="w-4 h-4" />,
  "7z": <BsFileZip className="w-4 h-4" />,
  tar: <BsFileZip className="w-4 h-4" />,
  gz: <BsFileZip className="w-4 h-4" />,
  exe: <BsFiletypeExe className="w-4 h-4" />,
  apk: <BsFiletypeExe className="w-4 h-4" />,
  dmg: <BsFiletypeExe className="w-4 h-4" />,
  iso: <BsFiletypeExe className="w-4 h-4" />,
};

export default function FileIcon({ fileName }: { fileName: string }) {
  if (!fileName) return <BoxIcon className="w-4 h-4" />;
  const ext = fileName.split(".").pop()?.toLowerCase();

  if (!ext) return <BoxIcon className="w-4 h-4" />;

  return extensionIconMap[ext] || <BoxIcon className="w-4 h-4" />;
}
